name: Auto-merge release-please

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge:
    if: "contains(github.event.pull_request.labels.*.name, 'autorelease: pending')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLEASE_PAT }}
          PR_URL: ${{ github.event.pull_request.html_url }}
